name: DevinHouse-actions

on:
  push:
    branches: [ main ]
  

  workflow_dispatch:

jobs:

  list:

    runs-on: ubuntu-latest
    steps:
      - name: listar arquivos
        run:  |
          ls ${{  github.workspace  }}
