name: DevinHouse-actions

on:
  push:
    
  workflow_dispatch:

jobs:

  secrets:

    runs-on: ubuntu-latest
    steps:
      - name: contar os segredos
        run: echo "i'll tell you my secret, it is ${{secrets.THE_SECRET}}"