name: DevinHouse-actions

on:
  push:
    branches: [ GH-actions exe4 ]
  workflow_dispatch:

jobs:

  list:

    runs-on: ubuntu-latest
    steps:
      - name: listar arquivos
        run: echo ${{secrets.THE_SECRET}}