name: DevinHouse-actions

on:
  push:
    branches: [ main ]
  

  workflow_dispatch:

jobs:

  ubuntu:

    runs-on: ubuntu-latest
    steps:
      - name: Rodando no Ubuntu
        run:  echo "Rodando não, ródando no ubuntu!"
    
  windows:
    runs-on:  windows-latest
    steps:
      - name: Rodando no windows
        run: echo "Rodando não, Ródando no windows!"
  terceiro:
    runs-on:  ubuntu-latest
    needs: [windows, ubuntu] 
    steps:
      - name: Rodando depois dos outros
        run: echo "Só vou rodar quando os caras de cima estiverem prontos!"
