name: DevinHouse-actions

on:
  push:
    branches: [ main ]
  

  workflow_dispatch:

jobs:

  list:

    runs-on: ubuntu-latest
    steps:
      - name: listar arquivos
        run:  |
          ls ${{  github.workspace  }}

      - name: Verificar node
        run: node --version
      - name: Verificar npm
        run:  npm --version
      - name: Verificar docker
        run:  docker info
